namespace HotellBookingSystem.Models;

/// <summary>
/// Base class for guests in the hotel system.
/// </summary>
public abstract class Guest
{
    private static int _guestCounter;
    private string _name = string.Empty;
    private string _email = string.Empty;
    private readonly List<Booking> _activeBookings = new();

    /// <summary>
    /// Unique guest id generated by the system.
    /// </summary>
    public string GuestId { get; }

    /// <summary>
    /// Guest name.
    /// </summary>
    public string Name
    {
        get => _name;
        set
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new ArgumentException("Name cannot be null or empty.", nameof(value));
            }

            _name = value;
        }
    }

    /// <summary>
    /// Guest email address.
    /// </summary>
    public string Email
    {
        get => _email;
        private set
        {
            if (string.IsNullOrWhiteSpace(value) || !value.Contains('@'))
            {
                throw new ArgumentException("Email must contain '@'.", nameof(value));
            }

            _email = value;
        }
    }

    /// <summary>
    /// Active bookings for the guest.
    /// </summary>
    public IReadOnlyList<Booking> ActiveBookings => _activeBookings.AsReadOnly();

    protected virtual int MaxActiveBookings => int.MaxValue;

    protected Guest(string name, string email)
    {
        GuestId = $"G{Interlocked.Increment(ref _guestCounter):000}";
        Name = name;
        Email = email;
    }

    /// <summary>
    /// Adds a booking to the guest if the booking limit allows it.
    /// </summary>
    internal void AddBooking(Booking booking)
    {
        if (booking is null)
        {
            throw new ArgumentNullException(nameof(booking));
        }

        EnsureBookingCapacity();

        _activeBookings.Add(booking);
    }

    /// <summary>
    /// Removes a booking from the guest's active list.
    /// </summary>
    internal void RemoveBooking(Booking booking)
    {
        if (booking is null)
        {
            throw new ArgumentNullException(nameof(booking));
        }

        _activeBookings.Remove(booking);
    }

    /// <summary>
    /// Calculates the price after any guest discount.
    /// </summary>
    public abstract decimal GetDiscount(decimal basePrice);

    internal void EnsureBookingCapacity()
    {
        if (_activeBookings.Count >= MaxActiveBookings)
            throw new InvalidOperationException($"A guest can have a maximum of {MaxActiveBookings} active bookings.");
    }
}
